[0m19:58:27.320170 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A72340E380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A72452E350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A72452E170>]}


============================== 19:58:27.325169 | 3aebf773-c696-42fb-b1c8-487d6eadb216 ==============================
[0m19:58:27.325169 [info ] [MainThread]: Running with dbt=1.9.1
[0m19:58:27.326169 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\gokul\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt compile --select dim_tickers_current', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:58:27.327170 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\DataEnggProject\airflow_dbt_stocks\airflow_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:58:27.328177 [debug] [MainThread]: Command `dbt compile` failed at 19:58:27.328177 after 0.11 seconds
[0m19:58:27.329173 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A72340E380>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A72452E440>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A72452E410>]}
[0m19:58:27.329173 [debug] [MainThread]: Flushing usage events
[0m19:58:27.635100 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:58:48.283626 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A63E2AE3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A63F3CE3B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A63F3CE1D0>]}


============================== 19:58:48.287621 | d30bd68b-052e-4224-83b7-9a40c4dd54e4 ==============================
[0m19:58:48.287621 [info ] [MainThread]: Running with dbt=1.9.1
[0m19:58:48.288626 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\gokul\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt compile --select dim_tickers_current', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:58:48.289626 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\DataEnggProject\airflow_dbt_stocks\airflow_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:58:48.290606 [debug] [MainThread]: Command `dbt compile` failed at 19:58:48.290606 after 0.08 seconds
[0m19:58:48.290606 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A63E2AE3E0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A63F3CE4A0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001A63F3CE470>]}
[0m19:58:48.291605 [debug] [MainThread]: Flushing usage events
[0m19:58:48.623715 [debug] [MainThread]: An error was encountered while trying to flush usage events
